apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-simple-register-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-simple-register
  template:
    metadata:
      labels:
        app: php-simple-register
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/php-simple-register-app/php-simple-register:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: register
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-password
