apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-simple-register-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-simple-register-app
  template:
    metadata:
      labels:
        app: php-simple-register-app
    spec:
      containers:
        - name: php
          image: image-registry.openshift-image-registry.svc:5000/php-simple-register/php-simple-register:latest
          ports:
            - containerPort: 8080
          env:
            - name: DOCUMENTROOT
              value: /var/www/html/app
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: register
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-password
